apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    name: postgres-config
    app: postgres-k8s-deployment
  namespace: nagpdemo
data:
  POSTGRES_DB: customers_db
  init.sql: |
    CREATE TABLE IF NOT EXISTS customer_accounts (
      id SERIAL PRIMARY KEY,
      first_name VARCHAR(255) NOT NULL,
      last_name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      phone_number VARCHAR(20) DEFAULT NULL,
      address VARCHAR(255) DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      created_by VARCHAR(255) DEFAULT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_by VARCHAR(255) DEFAULT NULL
    );